---
title: 8.8 패닉과 복구
aliases:
  - panic and recover
---

> [!NOTE] recover 를 사용하는 특정한 패턴
> 
> recover 는 패닉이 발생한 함수 내에서만 유효하다.
> 패닉이 발생한 함수 내에서 recover 를 호출하면, 패닉이 발생한 지점 이후의 코드를 실행할 수 있다.
> 패닉이 발생하면, defer 로 등록된 함수만 실행할 수 있기 때문에,
> recover 는 반드시 defer 내에서 호출해야 한다.
 

```go
package main

import (
	"fmt"
)

func div60(i int) {
	defer func() {
		if v := recover(); v != nil {
			fmt.Println(v) // prints "runtime error: integer divide by zero"
		}
	}()
	fmt.Println(60 / i)
}

func main() {
	for _, val := range []int{1, 2, 0, 6} {
		div60(val)
	}
}

``` 
